import SwiftUI

/// ELEVATE Typography Design Tokens
///
/// **AUTO-GENERATED** from `.elevate-themes/ios/primitives.css`
///
/// This file is automatically generated by `scripts/generate-typography-tokens.py`
/// to ensure typography values stay in sync with ELEVATE design tokens.
///
/// DO NOT EDIT THIS FILE MANUALLY - your changes will be overwritten!
///
/// To update typography:
/// 1. Edit `.elevate-themes/ios/primitives.css` (the source of truth)
/// 2. Run: `python3 scripts/generate-typography-tokens.py`
/// 3. Rebuild the ElevateUI package
///
/// Token Cascade:
/// - Layer 1: ELEVATE Core UI (WebSizes below - 1.25x smaller)
/// - Layer 2: iOS Adaptation (WebSizes × iosScaleFactor = iOS optimized)
/// - Layer 3: Components (Use Sizes enum, which can be themed)
@available(iOS 15, macOS 12, *)
public struct ElevateTypography {

    // MARK: - Base Sizes (ELEVATE Core UI Web Defaults)

    /// Typography base sizes from ELEVATE design tokens (web/desktop)
    /// These represent the original ELEVATE Core UI sizes before iOS scaling
    /// iOS sizes are calculated by applying iosScaleFactor (1.25×)
    ///
    /// **AUTO-GENERATED** from `.elevate-themes/ios/primitives.css`
    /// Do NOT edit manually - run `scripts/generate-typography-tokens.py`
    public enum WebSizes {
        // Display
        public static let displayLarge: CGFloat = 57.0  // iOS: 71.25pt
        public static let displayMedium: CGFloat = 45.0  // iOS: 56.25pt
        public static let displaySmall: CGFloat = 36.0  // iOS: 45.00pt

        // Headings
        public static let headingLarge: CGFloat = 32.0  // iOS: 40.00pt
        public static let headingMedium: CGFloat = 28.0  // iOS: 35.00pt
        public static let headingSmall: CGFloat = 24.0  // iOS: 30.00pt
        public static let headingXSmall: CGFloat = 20.0  // iOS: 25.00pt

        // Titles
        public static let titleLarge: CGFloat = 22.0  // iOS: 27.50pt
        public static let titleMedium: CGFloat = 16.0  // iOS: 20.00pt
        public static let titleSmall: CGFloat = 14.0  // iOS: 17.50pt

        // Body
        public static let bodyLarge: CGFloat = 16.0  // iOS: 20.00pt
        public static let bodyMedium: CGFloat = 14.0  // iOS: 17.50pt
        public static let bodySmall: CGFloat = 12.0  // iOS: 15.00pt

        // Labels
        public static let labelLarge: CGFloat = 16.0  // iOS: 20.00pt
        public static let labelMedium: CGFloat = 14.0  // iOS: 17.50pt
        public static let labelSmall: CGFloat = 12.0  // iOS: 15.00pt
        public static let labelXSmall: CGFloat = 11.0  // iOS: 13.75pt

        // Monospace
        public static let code: CGFloat = 14.0  // iOS: 17.50pt
        public static let codeSmall: CGFloat = 12.0  // iOS: 15.00pt

    }

    // MARK: - Themeable Sizes

    // MARK: - iOS Scale Factor

    /// iOS typography scale factor for mobile readability
    /// Applied to all ELEVATE Core UI base sizes for iOS platform
    public static let iosScaleFactor: CGFloat = 1.25  // +25% increase

    /// Themeable typography sizes that can be overridden by custom themes.
    /// Defaults to WebSizes × iosScaleFactor for optimal iOS readability.
    ///
    /// Example theme override:
    /// ```swift
    /// ElevateTypography.Sizes.displayLarge = 60  // Custom theme
    /// ```
    public enum Sizes {
        // Display
        public static var displayLarge: CGFloat = WebSizes.displayLarge * iosScaleFactor  // 71.25pt
        public static var displayMedium: CGFloat = WebSizes.displayMedium * iosScaleFactor  // 56.25pt
        public static var displaySmall: CGFloat = WebSizes.displaySmall * iosScaleFactor  // 45.00pt

        // Headings
        public static var headingLarge: CGFloat = WebSizes.headingLarge * iosScaleFactor  // 40.00pt
        public static var headingMedium: CGFloat = WebSizes.headingMedium * iosScaleFactor  // 35.00pt
        public static var headingSmall: CGFloat = WebSizes.headingSmall * iosScaleFactor  // 30.00pt
        public static var headingXSmall: CGFloat = WebSizes.headingXSmall * iosScaleFactor  // 25.00pt

        // Titles
        public static var titleLarge: CGFloat = WebSizes.titleLarge * iosScaleFactor  // 27.50pt
        public static var titleMedium: CGFloat = WebSizes.titleMedium * iosScaleFactor  // 20.00pt
        public static var titleSmall: CGFloat = WebSizes.titleSmall * iosScaleFactor  // 17.50pt

        // Body
        public static var bodyLarge: CGFloat = WebSizes.bodyLarge * iosScaleFactor  // 20.00pt
        public static var bodyMedium: CGFloat = WebSizes.bodyMedium * iosScaleFactor  // 17.50pt
        public static var bodySmall: CGFloat = WebSizes.bodySmall * iosScaleFactor  // 15.00pt

        // Labels
        public static var labelLarge: CGFloat = WebSizes.labelLarge * iosScaleFactor  // 20.00pt
        public static var labelMedium: CGFloat = WebSizes.labelMedium * iosScaleFactor  // 17.50pt
        public static var labelSmall: CGFloat = WebSizes.labelSmall * iosScaleFactor  // 15.00pt
        public static var labelXSmall: CGFloat = WebSizes.labelXSmall * iosScaleFactor  // 13.75pt

        // Monospace
        public static var code: CGFloat = WebSizes.code * iosScaleFactor  // 17.50pt
        public static var codeSmall: CGFloat = WebSizes.codeSmall * iosScaleFactor  // 15.00pt
    }

    // MARK: - Font Family

    /// Primary font family for ELEVATE typography
    public static let fontFamilyPrimary = "Inter"

    /// Monospace font family for code
    public static let fontFamilyMono = "RobotoMono"

    // MARK: - Font Weights

    public enum FontWeight {
        public static let regular: Font.Weight = .regular
        public static let medium: Font.Weight = .medium
        public static let semibold: Font.Weight = .semibold
        public static let bold: Font.Weight = .bold
    }

    // MARK: - Typography Styles (Web/Desktop)

    // Display
    public static let displayLarge = Font.custom(fontFamilyPrimary, size: Sizes.displayLarge)
    public static let displayMedium = Font.custom(fontFamilyPrimary, size: Sizes.displayMedium)
    public static let displaySmall = Font.custom(fontFamilyPrimary, size: Sizes.displaySmall)

    // Headings
    public static let headingLarge = Font.custom(fontFamilyPrimary, size: Sizes.headingLarge).weight(.bold)
    public static let headingMedium = Font.custom(fontFamilyPrimary, size: Sizes.headingMedium).weight(.bold)
    public static let headingSmall = Font.custom(fontFamilyPrimary, size: Sizes.headingSmall).weight(.semibold)
    public static let headingXSmall = Font.custom(fontFamilyPrimary, size: Sizes.headingXSmall).weight(.semibold)

    // Titles
    public static let titleLarge = Font.custom(fontFamilyPrimary, size: Sizes.titleLarge).weight(.semibold)
    public static let titleMedium = Font.custom(fontFamilyPrimary, size: Sizes.titleMedium).weight(.medium)
    public static let titleSmall = Font.custom(fontFamilyPrimary, size: Sizes.titleSmall).weight(.medium)

    // Body
    public static let bodyLarge = Font.custom(fontFamilyPrimary, size: Sizes.bodyLarge)
    public static let bodyMedium = Font.custom(fontFamilyPrimary, size: Sizes.bodyMedium)
    public static let bodySmall = Font.custom(fontFamilyPrimary, size: Sizes.bodySmall)

    // Labels
    public static let labelLarge = Font.custom(fontFamilyPrimary, size: Sizes.labelLarge).weight(.medium)
    public static let labelMedium = Font.custom(fontFamilyPrimary, size: Sizes.labelMedium).weight(.medium)
    public static let labelSmall = Font.custom(fontFamilyPrimary, size: Sizes.labelSmall).weight(.medium)
    public static let labelXSmall = Font.custom(fontFamilyPrimary, size: Sizes.labelXSmall).weight(.medium)

    // Monospace
    public static let code = Font.custom(fontFamilyMono, size: Sizes.code)
    public static let codeSmall = Font.custom(fontFamilyMono, size: Sizes.codeSmall)
}
